### ISSUE TITLE
Define example case study from Liander point of view

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/AIFES#1]
For the Ketenproject we are going to examine a concrete grid area as a case study. After expert consultation (Hans), the area around Middenmeer was picked by Liander+TenneT. Let’s describe that case/grid area and make a start with finding the relevant data.

HOW:

Make a confluence page to bundle all information.
Assume we use 2022 as a test case

:white_check_mark: Find the relevant measurements for the stations (of Liander and of TenneT if available) using the grafana dashboard

:white_check_mark: See if we can retrieve all relevant MSRs behind that station

Ask NIM to provide this (an e-mail and csv for now would be fine, to be is an api). If they cannot do this yet, ask JM to retrieve this from Hana.

:white_check_mark: Find relevant large customers (also connected directly to substation)

Ask NIM (automatic, generic) or Hans, of NIM can’t do it automatically (yet). Large customers behind MSRs can be retrieved from the MSR load estimator

Also see https://shiny-analytics.alliander.local/belastingprognosedashboard/

See if we can retrieve Carm and T-forecasts for those customers

:white_check_mark: Ask around at other teams if we can find/plot the topology of the grid (think of geodienst) behind Middenmeer (for example Vincent Koppen - they perform N-1 calculations).

Goal is to have a semi-clear picture of how Liander performs N-1 calculations (which data/tools are used) so we know what data/toosl are available for our case study

“Hoe check je bij een bepaald stuk net of het vol zit en of er klant wel/niet bij kan.”
Welke data?
Welke tools?
:white_check_mark: if required, define follow-up stories to retrieve other data sets

TEST:
We have one clear confluence page describing station Middenmeer, with a lot of relevant data bundled there
Follow-up stories for data retrieval if required/things are though.

**Comment by wfstoel** [comment]
Still need to push the data to a more public space such as the sharepoint.

**Comment by woutertromptennet** [comment]
Data from Liander has been compared to measurements from TenneT. These are almost identical, with some small remarks.

- Some large deviations in power are reflected differently. within the data Probably caused by differences in averaging/snapshot-methodology. Not a problem from TenneT point of view.
- The two measurements on 150kV align beyond nicely, although small differences are present (again: prob. caused by differences in averaging etc.).

Please see Sharepoint for analysis results.
