### ISSUE TITLE
Review Notebook TenneT

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/AIFES#11]
Please review the Notebook provided by Alliander.

Does the notebook work on your machine,
Is the content clear,
What additional functionality would be useful,
...

**Comment by woutertromptennet** [comment]
I just got rid of Conda ;-) venv/poetry is preferred.

Tip: never use relative paths, especially if you already use Pathlib.

Notebook is working on my machine. Got a nice feature importance graph in the end.
