### ISSUE TITLE
Compare improvements by T-forecasts customers and/or perfect T-forecasts customers

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/AIFES#12]

**Comment by MartijnCa** [comment]
There is a problem with the data quality. The sum of the C-ARM measurements of all clients behind the substation Middenmeer does not add up to the total of the measured load on the substation.

The analysis of this issue cannot be performed as planned, but I copied the results of a relevant previously performed analysis to the SharePoint: https://alliander.sharepoint.com/:f:/r/teams/PortfolioSO/Gedeelde%20documenten/Collaboration%20Allianer%20-%20TenneT%20T-Prognose/Data%20and%20results/Results/%2312_improvements_current_and_perfect_customer_power_forecasts?csf=1&web=1&e=vfXOly
