### ISSUE TITLE
Use OpenSTEF to create benchmark. - Alliander

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/AIFES#8]
DOR: refine this story after this issue is done https://github.com/alliander-opensource/AIFES/issues/17

Why/What:
As a starting point for the Comparison Testbed, we want to use the OpenSTEF backtest example notebook. Let's make it available in this repo and usable on the shared data. (Alliander)

How:
..

Result:
- A notebook to perform a backtest on the shared data is available in this repo, and can be used by other parties as well.

**Comment by MartijnCa** [comment]
Link to results in non-public sharepoint:
https://alliander.sharepoint.com/:f:/r/teams/PortfolioSO/Gedeelde%20documenten/Collaboration%20Allianer%20-%20TenneT%20T-Prognose/Data%20and%20results/Results/%238_Backtest_benchmark?csf=1&web=1&e=ps5dNZ
